In [1]:
#importing dependacies
import pandas as pd
import geopandas as gp

In [96]:
#reading in puma13 files
pums13 = pd.read_csv("../Data/PUMs_NY/PUMS_NY_2013/ss13hny.csv", dtype = {'PUMA':str})
print "PUMA 2013:\n", pums13.head()
print ""
#Reading in puma_nyc file and merging it
puma_nyc = pd.read_csv("../Data/PUMA_NYC/Use_this/PUMA_NYC.txt", dtype={'PUMACE10':str})
pums13nyc = pd.merge(pums13,puma_nyc, how='inner', left_on='PUMA',right_on='PUMACE10')
print "Merged files:\n", pums13nyc.head()

PUMA 2013:
  RT  SERIALNO  DIVISION   PUMA  REGION  ST   ADJHSG   ADJINC  WGTP  NP  \
0  H        10         2  01201       1  36  1000000  1007549   155   1
1  H        27         2  01000       1  36  1000000  1007549    31   3
2  H        30         2  03305       1  36  1000000  1007549    82   0
3  H        36         2  04011       1  36  1000000  1007549    95   1
4  H        58         2  01500       1  36  1000000  1007549    23   5

    ...    wgtp71  wgtp72  wgtp73  wgtp74  wgtp75  wgtp76  wgtp77  wgtp78  \
0   ...        46     166     166      44     127     267     260     259
1   ...        26      38      59      43      35      31       7      28
2   ...        81     131     126     133      78      81      24     134
3   ...        89      97     181      96      27      95      27      26
4   ...        27       6      10      35      32       7      23      38

   wgtp79  wgtp80
0     161      49
1      35      10
2      81      79
3     154      95
4       7      27

[5 rows x 231 columns]

Merged files:
  RT  SERIALNO  DIVISION   PUMA  REGION  ST   ADJHSG   ADJINC  WGTP  NP  \
0  H        36         2  04011       1  36  1000000  1007549    95   1
1  H       443         2  04011       1  36  1000000  1007549   175   7
2  H      2529         2  04011       1  36  1000000  1007549    79   7
3  H      9051         2  04011       1  36  1000000  1007549   147   0
4  H     10983         2  04011       1  36  1000000  1007549   187   2

     ...     wgtp80  FID  STATEFP10  PUMACE10        AFFGEOID10  GEOID10  \
0    ...         95   15         36     04011  7950000US3604011  3604011
1    ...         59   15         36     04011  7950000US3604011  3604011
2    ...         71   15         36     04011  7950000US3604011  3604011
3    ...        145   15         36     04011  7950000US3604011  3604011
4    ...        182   15         36     04011  7950000US3604011  3604011

                                              NAME10  LSAD10  ALAND10  \
0  NYC-Brooklyn Community District 9--Crown Heigh...      P0  4424283
1  NYC-Brooklyn Community District 9--Crown Heigh...      P0  4424283
2  NYC-Brooklyn Community District 9--Crown Heigh...      P0  4424283
3  NYC-Brooklyn Community District 9--Crown Heigh...      P0  4424283
4  NYC-Brooklyn Community District 9--Crown Heigh...      P0  4424283

   AWATER10
0         0
1         0
2         0
3         0
4         0

[5 rows x 240 columns]

In [101]:
#cols = list(pums13nyc.columns)
#cols

['RT',
 'SERIALNO',
 'DIVISION',
 'PUMA',
 'REGION',
 'ST',
 'ADJHSG',
 'ADJINC',
 'WGTP',
 'NP',
 'TYPE',
 'ACCESS',
 'ACR',
 'AGS',
 'BATH',
 'BDSP',
 'BLD',
 'BROADBND',
 'BUS',
 'COMPOTHX',
 'CONP',
 'DIALUP',
 'DSL',
 'ELEP',
 'FIBEROP',
 'FS',
 'FULP',
 'GASP',
 'HANDHELD',
 'HFL',
 'INSP',
 'LAPTOP',
 'MHP',
 'MODEM',
 'MRGI',
 'MRGP',
 'MRGT',
 'MRGX',
 'OTHSVCEX',
 'REFR',
 'RMSP',
 'RNTM',
 'RNTP',
 'RWAT',
 'RWATPR',
 'SATELLITE',
 'SINK',
 'SMP',
 'STOV',
 'TEL',
 'TEN',
 'TOIL',
 'VACS',
 'VALP',
 'VEH',
 'WATP',
 'YBL',
 'FES',
 'FFINCP',
 'FGRNTP',
 'FHINCP',
 'FINCP',
 'FPARC',
 'FSMOCP',
 'GRNTP',
 'GRPIP',
 'HHL',
 'HHT',
 'HINCP',
 'HUGCL',
 'HUPAC',
 'HUPAOC',
 'HUPARC',
 'KIT',
 'LNGI',
 'MULTG',
 'MV',
 'NOC',
 'NPF',
 'NPP',
 'NR',
 'NRC',
 'OCPIP',
 'PARTNER',
 'PLM',
 'PSF',
 'R18',
 'R60',
 'R65',
 'RESMODE',
 'SMOCP',
 'SMX',
 'SRNT',
 'SSMC',
 'SVAL',
 'TAXP',
 'WIF',
 'WKEXREL',
 'WORKSTAT',
 'FACCESSP',
 'FACRP',
 'FAGSP',
 'FBATHP',
 'FBDSP',
 'FBLDP',
 'FBROADBNDP',
 'FBUSP',
 'FCOMPOTHXP',
 'FCONP',
 'FDIALUPP',
 'FDSLP',
 'FELEP',
 'FFIBEROPP',
 'FFSP',
 'FFULP',
 'FGASP',
 'FHANDHELDP',
 'FHFLP',
 'FINSP',
 'FKITP',
 'FLAPTOPP',
 'FMHP',
 'FMODEMP',
 'FMRGIP',
 'FMRGP',
 'FMRGTP',
 'FMRGXP',
 'FMVP',
 'FOTHSVCEXP',
 'FPLMP',
 'FREFRP',
 'FRMSP',
 'FRNTMP',
 'FRNTP',
 'FRWATP',
 'FRWATPRP',
 'FSATELLITEP',
 'FSINKP',
 'FSMP',
 'FSMXHP',
 'FSMXSP',
 'FSTOVP',
 'FTAXP',
 'FTELP',
 'FTENP',
 'FTOILP',
 'FVACSP',
 'FVALP',
 'FVEHP',
 'FWATP',
 'FYBLP',
 'wgtp1',
 'wgtp2',
 'wgtp3',
 'wgtp4',
 'wgtp5',
 'wgtp6',
 'wgtp7',
 'wgtp8',
 'wgtp9',
 'wgtp10',
 'wgtp11',
 'wgtp12',
 'wgtp13',
 'wgtp14',
 'wgtp15',
 'wgtp16',
 'wgtp17',
 'wgtp18',
 'wgtp19',
 'wgtp20',
 'wgtp21',
 'wgtp22',
 'wgtp23',
 'wgtp24',
 'wgtp25',
 'wgtp26',
 'wgtp27',
 'wgtp28',
 'wgtp29',
 'wgtp30',
 'wgtp31',
 'wgtp32',
 'wgtp33',
 'wgtp34',
 'wgtp35',
 'wgtp36',
 'wgtp37',
 'wgtp38',
 'wgtp39',
 'wgtp40',
 'wgtp41',
 'wgtp42',
 'wgtp43',
 'wgtp44',
 'wgtp45',
 'wgtp46',
 'wgtp47',
 'wgtp48',
 'wgtp49',
 'wgtp50',
 'wgtp51',
 'wgtp52',
 'wgtp53',
 'wgtp54',
 'wgtp55',
 'wgtp56',
 'wgtp57',
 'wgtp58',
 'wgtp59',
 'wgtp60',
 'wgtp61',
 'wgtp62',
 'wgtp63',
 'wgtp64',
 'wgtp65',
 'wgtp66',
 'wgtp67',
 'wgtp68',
 'wgtp69',
 'wgtp70',
 'wgtp71',
 'wgtp72',
 'wgtp73',
 'wgtp74',
 'wgtp75',
 'wgtp76',
 'wgtp77',
 'wgtp78',
 'wgtp79',
 'wgtp80',
 'FID',
 'STATEFP10',
 'PUMACE10',
 'AFFGEOID10',
 'GEOID10',
 'NAME10',
 'LSAD10',
 'ALAND10',
 'AWATER10']

In [113]:
p13 = pums13nyc[['PUMA','WGTP', 'ACCESS', 'BROADBND', 'COMPOTHX', 'DIALUP', 'DSL', 'FIBEROP','MODEM', 'SATELLITE',\
                'OTHSVCEX','HANDHELD','LAPTOP']]
p13.head()

,PUMA,WGTP,ACCESS,BROADBND,COMPOTHX,DIALUP,DSL,FIBEROP,MODEM,SATELLITE,OTHSVCEX,HANDHELD,LAPTOP
0,04011,95,1,2,2,2,2,2,1,2,2,1,1
1,04011,175,1,2,2,1,1,2,1,2,2,2,1
2,04011,79,1,2,2,2,2,2,1,2,2,1,1
3,04011,147,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,04011,187,1,2,2,2,2,2,1,2,2,1,1

In [120]:
inter = pums13nyc[['PUMA','WGTP', 'ACCESS', 'BROADBND', 'DIALUP', 'DSL', 'FIBEROP','MODEM', 'SATELLITE','OTHSVCEX']]
inter.head()

,PUMA,WGTP,ACCESS,BROADBND,DIALUP,DSL,FIBEROP,MODEM,SATELLITE,OTHSVCEX
0,04011,95,1,2,2,2,2,1,2,2
1,04011,175,1,2,1,1,2,1,2,2
2,04011,79,1,2,2,2,2,1,2,2
3,04011,147,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,04011,187,1,2,2,2,2,1,2,2

In [122]:
inter2 = inter.dropna(how = 'all', thresh = 1, subset = ['ACCESS', 'BROADBND', 'DIALUP', 'DSL', 'FIBEROP',\
                                                            'MODEM', 'SATELLITE','OTHSVCEX'])
inter2.head()

,PUMA,WGTP,ACCESS,BROADBND,DIALUP,DSL,FIBEROP,MODEM,SATELLITE,OTHSVCEX
0,04011,95,1,2,2,2,2,1,2,2
1,04011,175,1,2,1,1,2,1,2,2
2,04011,79,1,2,2,2,2,1,2,2
4,04011,187,1,2,2,2,2,1,2,2
5,04011,87,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [156]:
PUMAreas=inter2.groupby('PUMA')

In [186]:
PUMAreas=pums13nyc.groupby('PUMA')

In [187]:
Tot_HH = (PUMAreas.WGTP.sum()).sum()
print "Total number of Households in NYC: {0:,}".format(Tot_HH) #No of HH in NYC

Total number of Households in NYC: 3,394,486

In [162]:
print "ACCESS\n"
TotAccess1 = inter2.ix[inter2.ACCESS==1].WGTP.sum()
print "Number of HH with internet and subscription: {0:,} ({1:.2f}%)" .format(TotAccess1,(TotAccess1/float(Tot_HH))*100)

TotAccess2 = inter2.ix[inter2.ACCESS==2].WGTP.sum()
print "Number of HH with internet but no subscription: {0:,} ({1:.2f}%)" .format(TotAccess2,(TotAccess2/float(Tot_HH))*100)

TotAccess3 = inter2.ix[inter2.ACCESS==3].WGTP.sum()
print "Number of HH without internet: {0:,} ({1:.2f}%)" .format(TotAccess3,(TotAccess3/float(Tot_HH))*100)

ACCESS

Number of HH with internet and subscription: 2,296,941 (74.46%)
Number of HH with internet but no subscription: 113,458 (3.68%)
Number of HH without internet: 674,463 (21.86%)

In [164]:
print "BROADBND\n"
TotBROADBND1 = inter2.ix[inter2.BROADBND==1].WGTP.sum()
print "Number of HH with internet: {0:,} ({1:.2f}%)" .format(TotBROADBND1,(TotBROADBND1/float(Tot_HH))*100)

TotBROADBND2 = inter2.ix[inter2.BROADBND==2].WGTP.sum()
print "Number of HH without internet: {0:,} ({1:.2f}%)" .format(TotBROADBND2,(TotBROADBND2/float(Tot_HH))*100)

print 'Alternatvely:'
TotBROADBND21 = Tot_HH-TotBROADBND1
print "Number of HH without internet: {0:,} ({1:.2f}%)" .format(TotBROADBND21,(TotBROADBND21/float(Tot_HH))*100)

BROADBND

Number of HH with internet: 886,847 (28.75%)
Number of HH without internet: 1,410,094 (45.71%)
alternatvely:
Number of HH without internet: 2,198,015 (71.25%)

In [169]:
#DSL
TotDSL1 = inter2.ix[inter2.DSL==1].WGTP.sum()
TotDSL2 = inter2.ix[inter2.DSL==2].WGTP.sum()
TotDSL21 = Tot_HH-TotDSL1

#Printing DSL
print "DSL\n"
print "Number of HH with internet: {0:,} ({1:.2f}%)" .format(TotDSL1,(TotDSL1/float(Tot_HH))*100)
print "Number of HH without internet: {0:,} ({1:.2f}%)" .format(TotDSL2,(TotDSL2/float(Tot_HH))*100)
print 'Alternatvely:'
print "Number of HH without internet: {0:,} ({1:.2f}%)" .format(TotDSL21,(TotDSL21/float(Tot_HH))*100)

DSL

Number of HH with internet: 403,670 (13.09%)
Number of HH without internet: 1,893,271 (61.37%)
Alternatvely:
Number of HH without internet: 2,681,192 (86.91%)

In [185]:
print "ACS \"BROADBND\"\n"
TotFIBEROP1 = inter2.ix[inter2.FIBEROP==1].WGTP.sum()
TotMODEM1 = inter2.ix[inter2.MODEM==1].WGTP.sum()
TotSATELLITE1 = inter2.ix[inter2.SATELLITE==1].WGTP.sum()

Tot_ACS_BRDBND1 = TotBROADBND1+TotDSL1+TotFIBEROP1+TotMODEM1+TotSATELLITE1
Tot_ACS_BRDBND21 = Tot_HH-Tot_ACS_BRDBND1

Tot_ACS_BRDBND11 = inter2.ix[(inter2.BROADBND==1)|(inter2.DSL==1)|(inter2.FIBEROP==1)|(inter2.MODEM==1)|(inter2.SATELLITE==1)].WGTP.sum()
Tot_ACS_BRDBND211 = Tot_HH-Tot_ACS_BRDBND11
print "Number of HH with internet: {0:,} ({1:.2f}%)" .format(Tot_ACS_BRDBND1,(Tot_ACS_BRDBND1/float(Tot_HH))*100)
print "Number of HH without internet: {0:,} ({1:.2f}%)" .format(Tot_ACS_BRDBND21,(Tot_ACS_BRDBND21/float(Tot_HH))*100)

print "\n\nClearly, a bunch of people with internet have mobile phone broaband too"

print "Better Computation:\n"
print "Number of HH with internet: {0:,} ({1:.2f}%)" .format(Tot_ACS_BRDBND11,(Tot_ACS_BRDBND11/float(Tot_HH))*100)
print "Number of HH without internet: {0:,} ({1:.2f}%)" .format(Tot_ACS_BRDBND211,(Tot_ACS_BRDBND211/float(Tot_HH))*100)

ACS "BROADBND"

Number of HH with internet: 3,374,231 (109.38%)
Number of HH without internet: -289,369 (-9.38%)


Clearly, a bunch of people with internet have mobile phone broaband too
Better Computation:

Number of HH with internet: 2,272,025 (73.65%)
Number of HH without internet: 812,837 (26.35%)

In [183]:
Tot_ACS_BRDBND11 = inter2.ix[(inter2.BROADBND==1)|(inter2.DSL==1)|(inter2.FIBEROP==1)|(inter2.MODEM==1)|(inter2.SATELLITE==1)].WGTP.sum()